# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7325f635649eacd491019b8d9908e227681ad8b98d4c2fc0c5016754d3c0cdfd044cbb3c91172d1abb385924ce17b61d871b9fa7151b98fa196da78e78e68bf6

test:
  secret_key_base: 8c9f0db25f794cc7f85ef718bf02bc606dbe11afe30bfd4baa48ceccf644b883a31f590ee886da51c32be519127914fe86b198b2833106112cd24093ae30b114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
